### ISSUE TITLE
Update Instructions To Reboot After Patching

### ISSUE THREAD

**Issue by bdkjones** [sdaqo/k3s-killer#1]
I followed the instructions verbatim, but found that after killing the `k3s-server` process (either by using the script's kill command OR by running `kill -9 [PID]` directly), the server process respawned under a new PID. I can see it with `top`.

I confirmed that the patches were applied. Here's the output if I run `install` a second time:

![Screenshot 2024-03-06 at 17 02 53](https://github.com/sdaqo/k3s-killer/assets/926566/1ace1128-d902-44db-8e1d-013b50fb6daf)

And here's the contents of the k3s service file showing `restart=never`:

![Screenshot 2024-03-06 at 17 03 43](https://github.com/sdaqo/k3s-killer/assets/926566/104f71ec-b416-4664-805b-ef440264535c)

## The Fix

I figured that the configuration might be cached somewhere, so I rebooted the system and killed `k3s-server` again. This time it stayed dead. 

I think your current instructions might work if a user is modifying the system BEFORE k3s is running at all. But for those who already have it spun up, rebooting between applying the patches and killing `k3s-server` seems to be necessary.

**Comment by sdaqo** [comment]
Ah you are right, after changing the service you have to do `systemctl daemon-reload`, totally forgot that, thanks for the report!
