### ISSUE TITLE
Install Fails on Dragonfish

### ISSUE THREAD

**Issue by bdkjones** [sdaqo/k3s-killer#2]
After updating to the release version of Dragonfish (24.04.0), I attempted to reinstall k3s-killer, but was met with an error about the filesystem being read-only. The install script suggested (apparently incorrectly) that k3s-killer was successfully installed, but the k3s-server process regenerates immediately when killed.

I made no changes to this system other than upgrading to Dragonfish. Attempting to `sudo rm /usr/local/bin/k3s-kill.sh` *also* fails the same "read-only filesystem" message.

![Screenshot 2024-04-29 at 14 42 40](https://github.com/sdaqo/k3s-killer/assets/926566/48fad613-ef7a-4683-9b2c-c892d9c4bb76)

**Comment by bdkjones** [comment]
It was sufficient to run this:

```
sudo zfs set readonly=off boot-pool/ROOT/24.04.0/usr
```

The install then proceeded, but with a warning about failed hunks. Using the `kill` command through the script failed, as shown, but directly invoking `kill -9 [PID of K3S_Server]` worked: the thing is dead and staying dead.

![Screenshot 2024-04-29 at 14 58 40](https://github.com/sdaqo/k3s-killer/assets/926566/4ca8d3f1-3ed5-42d7-b23f-60ae0090f6d0)

**Comment by sdaqo** [comment]
thanks for your reports, will look into it

**Comment by sdaqo** [comment]
I now added a fix and a update to the readme!
